if get_time ( ) > pc . getqf ( "duration" ) or is_test_server ( ) then 
say_title ( locale_quest ( 529 ) ) 
say ( locale_quest ( 530 ) ) 
pc . remove_item ( 30167 , 1 ) 
pc . setqf ( "duration" , ( get_time ( ) + ( 60 * 60 * 7 ) ) ) 
wait ( ) 
local pass_percent 
if affect . get_apply_value ( 400 ) == nil then 
pass_percent = 60 
else 
pass_percent = 90 
end 
test_chat ( string . format ( "pass percent %d" , pass_percent ) ) 
local s = number ( 1 , 100 ) 
if s <= pass_percent then 
if pc . getqf ( "collect_count" ) < 39 then 
local index = pc . getqf ( "collect_count" ) + 1 
pc . setqf ( "collect_count" , index ) 
say_title ( locale_quest ( 531 ) ) 
say ( locale_quest ( 532 ) ) 
say ( locale_quest ( 533 .. " " .. locale_quest ( 534 ) , ( 40 - pc . getqf ( "collect_count" ) ) ) ) 
say ( locale_quest ( 535 ) ) 
affect . remove ( 400 ) 
return 
end 
say_title ( locale_quest ( 536 ) ) 
say ( locale_quest ( 537 ) ) 
pc . setqf ( "duration" , 0 ) 
pc . setqf ( "collect_count" , 0 ) 
affect . remove ( 400 ) 
set_state ( "key_item" ) 
return 
else 
say_title ( locale_quest ( 538 ) ) 
say ( locale_quest ( 539 ) ) 
affect . remove ( 400 ) 
return 
end 
else 
say_title ( locale_quest ( 540 ) ) 
say ( locale_quest ( 541 ) ) 
return 
end 
