if get_time ( ) > pc . getqf ( "duration" ) or is_test_server ( ) then 
if pc . count_item ( 30015 ) > 0 then 
say_title ( locale_quest ( 211 ) ) 
say ( locale_quest ( 375 ) ) 
pc . remove_item ( 30015 , 1 ) 
pc . setqf ( "duration" , ( get_time ( ) + ( 60 * 60 * 3 ) ) ) 
wait ( ) 
local pass_percent 
if affect . get_apply_value ( 400 ) == nil then 
pass_percent = 60 
else 
pass_percent = 90 
end 
test_chat ( string . format ( "pass percent %d" , pass_percent ) ) 
local s = number ( 1 , 100 ) 
if s <= pass_percent then 
if pc . getqf ( "collect_count" ) < 14 then 
local index = pc . getqf ( "collect_count" ) + 1 
pc . setqf ( "collect_count" , index ) 
say_title ( locale_quest ( 211 ) ) 
say ( locale_quest ( 376 , ( 15 - pc . getqf ( "collect_count" ) ) ) ) 
affect . remove ( 400 ) 
return 
end 
say_title ( locale_quest ( 211 ) ) 
say ( locale_quest ( 377 ) ) 
pc . setqf ( "duration" , 0 ) 
pc . setqf ( "collect_count" , 0 ) 
affect . remove ( 400 ) 
set_state ( "key_item" ) 
return 
else 
say_title ( locale_quest ( 211 ) ) 
say ( locale_quest ( 378 ) ) 
affect . remove ( 400 ) 
return 
end 
else 
say_title ( locale_quest ( 211 ) ) 
say ( locale_quest ( 379 ) ) 
return 
end 
else 
say_title ( locale_quest ( 211 ) ) 
say ( locale_quest ( 381 ) ) 
return 
end 
