if pc . get_level ( ) < 5 then 
say_title ( locale_quest ( 689 ) ) 
say ( locale_quest ( 8159 ) ) 
return 
end 
if pc . get_level ( ) > 30 then 
say_title ( locale_quest ( 689 ) ) 
say ( locale_quest ( 8160 , pc . get_level ( ) ) ) 
return 
end 
if pc . get_skill_group ( ) == 0 then 
say_title ( locale_quest ( 689 ) ) 
say ( locale_quest ( 8161 ) ) 
return 
end 
local cost = 10000 + pc . get_level ( ) * 2000 
local s = 0 
if not pc . has_master_skill ( ) then 
say_title ( locale_quest ( 689 ) ) 
say ( locale_quest ( 8162 , cost ) ) 
s = select ( locale_quest ( 8153 ) , locale_quest ( 8163 ) ) 
else 
say_title ( locale_quest ( 689 ) ) 
say ( locale_quest ( 8164 ) ) 
wait ( ) 
say ( locale_quest ( 8165 , cost ) ) 
s = select ( locale_quest ( 8166 ) , locale_quest ( 2426 ) ) 
end 
if 2 == s then 
say_title ( locale_quest ( 689 ) ) 
say ( locale_quest ( 8154 ) ) 
return 
end 
if pc . get_gold ( ) < cost then 
say_title ( locale_quest ( 689 ) ) 
say ( locale_quest ( 8155 ) ) 
return 
end 
pc . change_gold ( - cost ) 
pc . clear_skill ( ) 
pc . set_skill_group ( 0 ) 
set_quest_state ( "skill_group" , "run" ) 
