say_title ( locale_quest ( 2090 ) ) 
say ( locale_quest ( 2217 ) ) 
local b = select ( locale_quest ( 10928 ) , locale_quest ( 10929 ) ) 
if 1 == b then 
if pc . get_money ( ) >= 50000 then 
pc . changemoney ( - 50000 ) 
say_title ( locale_quest ( 2090 ) ) 
say ( locale_quest ( 2218 ) ) 
pc . give_item2 ( 50052 , 1 ) 
else 
say ( locale_quest ( 2219 ) ) 
end 
elseif 2 == b then return 
else 
say ( locale_quest ( 1298 , b ) ) 
end 
