say_title ( locale_quest ( 2090 ) ) 
say ( locale_quest ( 2192 ) ) 
local b = select ( locale_quest ( 10928 ) , locale_quest ( 10929 ) ) 
if 1 == b then 
if pc . get_money ( ) >= 100000 then 
pc . changemoney ( - 100000 ) 
say_title ( locale_quest ( 114 ) ) 
say ( locale_quest ( 2193 ) ) 
pc . give_item2 ( 50053 , 1 ) 
else 
say_title ( locale_quest ( 2090 ) ) 
say ( locale_quest ( 2219 ) ) 
end 
elseif 2 == b then return 
else 
say ( locale_quest ( 1298 , b ) ) 
end 
