if not npc . lock ( ) then 
say_title ( locale_quest ( 6541 ) ) 
say ( locale_quest ( 6552 ) ) 
return 
end 
say_title ( locale_quest ( 6534 ) ) 
say ( locale_quest ( 6554 ) ) 
local s = select ( locale_quest ( 6555 ) , locale_quest ( 6556 ) ) 
if s == 2 then 
local u_vid = marriage . find_married_vid ( ) 
local old = pc . select ( u_vid ) 
pc . select ( old ) 
if u_vid == 0 then 
say_title ( locale_quest ( 6534 ) ) 
say ( locale_quest ( 6557 ) ) 
npc . unlock ( ) 
return 
end 
say_title ( locale_quest ( 6534 ) ) 
say ( locale_quest ( 6558 ) ) 
local ok_sign = confirm ( u_vid , locale_quest ( 6559 , 30 ) ) 
if ok_sign == CONFIRM_OK then 
marriage . end_wedding ( ) 
else 
say_title ( locale_quest ( 6541 ) ) 
say ( locale_quest ( 6560 ) ) 
end 
end 
npc . unlock ( ) 
