if get_time ( ) > pc . getqf ( "duration" ) or is_test_server ( ) then 
if pc . count_item ( 30168 ) > 0 then 
say_title ( mob_name ( 20084 ) ) 
say ( locale_quest ( 584 ) ) 
pc . remove_item ( 30168 , 1 ) 
pc . setqf ( "duration" , ( get_time ( ) + ( 60 * 60 * 8 ) ) ) 
wait ( ) 
local pass_percent 
if affect . get_apply_value ( 400 ) == nil then 
pass_percent = 60 
else 
pass_percent = 90 
end 
test_chat ( string . format ( "pass percent %d" , pass_percent ) ) 
local s = number ( 1 , 100 ) 
if s <= pass_percent then 
if pc . getqf ( "collect_count" ) < 49 then 
local index = pc . getqf ( "collect_count" ) + 1 
pc . setqf ( "collect_count" , index ) 
say_title ( mob_name ( 20084 ) ) 
say ( locale_quest ( 585 ) ) 
say ( locale_quest ( 588 , ( 50 - pc . getqf ( "collect_count" ) ) ) ) 
say ( locale_quest ( 589 ) ) 
affect . remove ( 400 ) 
return 
end 
say_title ( mob_name ( 20084 ) ) 
say ( locale_quest ( 590 ) ) 
pc . setqf ( "duration" , 0 ) 
pc . setqf ( "collect_count" , 0 ) 
affect . remove ( 400 ) 
set_state ( "key_item" ) 
return 
else 
say_title ( mob_name ( 20084 ) ) 
say ( locale_quest ( 591 ) ) 
affect . remove ( 400 ) 
return 
end 
else 
say ( mob_name ( 20084 ) ) 
say ( locale_quest ( 592 ) ) 
return 
end 
else 
say_title ( mob_name ( 20084 ) ) 
say ( locale_quest ( 593 ) ) 
return 
end 
