if get_time ( ) > pc . getqf ( "duration" ) or is_test_server ( ) then 
if pc . count_item ( 30050 ) > 0 then 
say_title ( locale_quest ( 409 ) ) 
say ( locale_quest ( 412 ) ) 
pc . remove_item ( 30050 , 1 ) 
pc . setqf ( "duration" , ( get_time ( ) + ( 60 * 60 * 4 ) ) ) 
wait ( ) 
local pass_percent 
if affect . get_apply_value ( 400 ) == nil then 
pass_percent = 60 
else 
pass_percent = 90 
end 
test_chat ( string . format ( "pass percent %d" , pass_percent ) ) 
local s = number ( 1 , 100 ) 
if s <= pass_percent then 
if pc . getqf ( "collect_count" ) < 19 then 
local index = pc . getqf ( "collect_count" ) + 1 
pc . setqf ( "collect_count" , index ) 
say_title ( locale_quest ( 409 ) ) 
say ( locale_quest ( 413 , ( 20 - pc . getqf ( "collect_count" ) ) ) ) 
affect . remove ( 400 ) 
return 
end 
say_title ( locale_quest ( 409 ) ) 
say ( locale_quest ( 414 ) ) 
pc . setqf ( "duration" , 0 ) 
pc . setqf ( "collect_count" , 0 ) 
affect . remove ( 400 ) 
set_state ( "key_item" ) 
return 
else 
say_title ( locale_quest ( 409 ) ) 
say ( locale_quest ( 416 ) ) 
affect . remove ( 400 ) 
return 
end 
else 
say_title ( locale_quest ( 409 ) ) 
say ( locale_quest ( 417 ) ) 
return 
end 
else 
say_title ( locale_quest ( 409 ) ) 
say ( locale_quest ( 418 ) ) 
return 
end 
