say_title ( locale_quest ( 201 ) ) 
say ( locale_quest ( 202 ) ) 
pc . remove_item ( 50701 , 1 ) 
wait ( ) 
local pass_percent 
if affect . get_apply_value ( 400 ) == nil then 
pass_percent = 90 
else 
pass_percent = 100 
end 
local s = number ( 1 , 100 ) 
if s <= pass_percent then 
if pc . getqf ( "collect_count" ) < 4 then 
local index = pc . getqf ( "collect_count" ) + 1 
pc . setqf ( "collect_count" , index ) 
say_title ( locale_quest ( 211 ) ) 
say ( locale_quest ( 263 , 5 - pc . getqf ( "collect_count" ) ) ) 
affect . remove ( 400 ) 
return 
end 
say_title ( locale_quest ( 211 ) ) 
say ( locale_quest ( 264 ) ) 
say_title ( locale_quest ( 265 ) ) 
say_reward ( locale_quest ( 266 ) ) 
pc . setqf ( "collect_count" , 0 ) 
affect . remove ( 400 ) 
clear_letter ( ) 
set_state ( "__complete" ) 
if pc . get_job ( ) == 3 then 
pc . give_item2 ( 7004 ) 
say_reward ( locale_quest ( 267 ) ) 
return 
else 
pc . give_item2 ( 14 ) 
say_reward ( locale_quest ( 268 ) ) 
end 
pc . change_money ( 1000 ) 
pc . give_exp2 ( 500 ) 
else 
say_title ( locale_quest ( 211 ) ) 
say ( locale_quest ( 269 ) ) 
affect . remove ( 400 ) 
return 
end 
