say_title ( mob_name ( 9012 ) ) 
say ( locale_quest ( 6454 ) ) 
local select1 = select ( locale_quest ( 6555 ) , locale_quest ( 6556 ) ) 
if select1 == 1 then 
say_title ( mob_name ( 9012 ) ) 
say ( locale_quest ( 6455 ) ) 
local cost = 50000 
if pc . get_level ( ) >= 90 then 
cost = cost + ( ( pc . get_level ( ) - 90 ) * 10000 ) 
end 
say_reward ( locale_quest ( 6456 , cost ) ) 
local select2 = select ( locale_quest ( 6555 ) , locale_quest ( 6556 ) ) 
if select2 == 1 and pc . get_level ( ) >= 90 and pc . get_gold ( ) >= cost then 
pc . changegold ( - cost ) 
pc . warp ( 1.1043e+06 , 1.7885e+06 ) 
else 
if pc . get_gold ( ) < cost then 
say_title ( locale_quest ( 6444 ) ) 
say ( locale_quest ( 6435 ) ) 
say_reward ( locale_quest ( 6437 , cost ) ) 
return 
end 
end 
else 
return 
end 
