say_title ( locale_quest ( 6444 ) ) 
say ( locale_quest ( 6458 ) ) 
local main_set = select ( locale_quest ( 6555 ) , locale_quest ( 6556 ) ) 
if main_set == 2 then 
return 
end 
if pc . get_level ( ) <= 10 then 
say_title ( locale_quest ( 6444 ) ) 
say ( locale_quest ( 6472 ) ) 
return 
end 
local map = pc . get_map_index ( ) 
local empire = pc . get_empire ( ) 
local level = pc . get_level ( ) 
local cost = math . floor ( level / 5 ) * 1000 
if cost < 1000 then 
cost = 1000 
end 
say_title ( locale_quest ( 6444 ) ) 
say ( locale_quest ( 6476 ) ) 
say_reward ( locale_quest ( 6477 , cost ) ) 
if map == 1 or map == 3 or map == 21 or map == 23 or map == 41 or map == 43 then 
local guild_map_names = { 
locale_quest ( 6426 ) , 
locale_quest ( 6428 ) , 
locale_quest ( 6430 ) , 
} 
guild_map_name = guild_map_names [ empire ] 
local added_guild_map = { 
locale_quest ( 6438 ) , 
locale_quest ( 6440 ) , 
locale_quest ( 6442 ) , 
} 
added_guild_map = added_guild_map [ empire ] 
local empire_castle = { 
locale_quest ( 6432 ) , 
locale_quest ( 6434 ) , 
locale_quest ( 6436 ) , 
} 
empire_castle = empire_castle [ empire ] 
local sub_set = 0 
if level < 40 then 
if pc . count_item ( 30180 ) == 0 then 
sub_set = select ( guild_map_name , locale_quest ( 1434 ) , locale_quest ( 1437 ) , locale_quest ( 1435 ) , added_guild_map , locale_quest ( 1650 ) ) 
if sub_set == 6 then 
return 
end 
else 
sub_set = select ( guild_map_name , locale_quest ( 1434 ) , locale_quest ( 1437 ) , locale_quest ( 1435 ) , added_guild_map , locale_quest ( 6475 ) , locale_quest ( 1650 ) ) 
if sub_set == 7 then 
return 
end 
end 
else 
if pc . count_item ( 30180 ) == 0 then 
sub_set = select ( guild_map_name , locale_quest ( 1434 ) , locale_quest ( 1437 ) , locale_quest ( 1435 ) , added_guild_map , locale_quest ( 8032 ) ) 
else 
sub_set = select ( guild_map_name , locale_quest ( 1434 ) , locale_quest ( 1437 ) , locale_quest ( 1435 ) , added_guild_map , locale_quest ( 6475 ) , locale_quest ( 8032 ) ) 
end 
if sub_set == 6 and pc . count_item ( 30180 ) == 0 then 
sub_set = sub_set + 1 
end 
if sub_set == 7 then 
say_title ( locale_quest ( 6444 ) ) 
say ( locale_quest ( 6480 ) ) 
say_reward ( locale_quest ( 6484 , cost ) ) 
sub_set = select ( locale_quest ( 1436 ) , locale_quest ( 6485 ) , locale_quest ( 6486 ) , locale_quest ( 6487 ) , locale_quest ( 6488 ) , locale_quest ( 1650 ) ) + 6 
if sub_set == 12 then 
return 
end 
if sub_set == 11 then 
say_title ( locale_quest ( 6444 ) ) 
say ( locale_quest ( 6424 ) ) 
say_reward ( locale_quest ( 6427 , cost ) ) 
if pc . count_item ( 30180 ) == 0 then 
sub_set = select ( guild_map_name , locale_quest ( 1434 ) , locale_quest ( 1437 ) , locale_quest ( 1435 ) , added_guild_map , locale_quest ( 8032 ) ) 
else 
sub_set = select ( guild_map_name , locale_quest ( 1434 ) , locale_quest ( 1437 ) , locale_quest ( 1435 ) , added_guild_map , locale_quest ( 6475 ) , locale_quest ( 8032 ) ) 
end 
if sub_set == 6 and pc . count_item ( 30180 ) == 0 then 
sub_set = sub_set + 1 
end 
if sub_set == 7 then 
say_title ( locale_quest ( 6444 ) ) 
say ( locale_quest ( 6431 ) ) 
say_reward ( locale_quest ( 6433 , cost ) ) 
sub_set = select ( locale_quest ( 1436 ) , locale_quest ( 6485 ) , locale_quest ( 6486 ) , locale_quest ( 6487 ) , locale_quest ( 1650 ) ) + 6 
if sub_set == 11 then 
return 
end 
end 
end 
end 
end 
if pc . get_gold ( ) < cost then 
say_title ( locale_quest ( 6444 ) ) 
say ( locale_quest ( 6435 ) ) 
say_reward ( locale_quest ( 6437 , cost ) ) 
return 
end 
pc . changegold ( - cost ) 
local warp = { 
{ 
{ 135600 , 4300 } , 
{ 179500 , 1000 } , 
{ 271800 , 13000 } , 
} , 
{ 
{ 402100 , 673900 } , 
{ 270400 , 739900 } , 
{ 321300 , 808000 } , 
} , 
{ 
{ 217800 , 627200 } , 
{ 221900 , 502700 } , 
{ 344000 , 502500 } , 
} , 
{ 
{ 434200 , 290600 } , 
{ 375200 , 174900 } , 
{ 491800 , 173600 } , 
} , 
{ 
{ 204800 , 204800 } , 
{ 614400 , 384000 } , 
{ 256000 , 819200 } , 
} , 
{ 
{ 287800 , 799700 } , 
{ 275500 , 800000 } , 
{ 277000 , 788000 } , 
} , 
{ 
{ 599400 , 756300 } , 
{ 597800 , 622200 } , 
{ 730700 , 689800 } , 
} , 
{ 
{ 590500 , 110500 } , 
{ 590500 , 110500 } , 
{ 590500 , 110500 } , 
} , 
{ 
{ 290000 , 5600 } , 
{ 290000 , 5600 } , 
{ 290000 , 5600 } , 
} , 
{ 
{ 1.1195e+06 , 70200 } , 
{ 1.1195e+06 , 70200 } , 
{ 1.1195e+06 , 70200 } , 
} , 
} 
test_chat ( warp [ sub_set ] [ empire ] [ 1 ] .. warp [ sub_set ] [ empire ] [ 2 ] ) 
say_title ( locale_quest ( 6444 ) ) 
say ( locale_quest ( 6439 ) ) 
wait ( ) 
if pc . is_dead ( ) == false then 
pc . warp ( warp [ sub_set ] [ empire ] [ 1 ] , warp [ sub_set ] [ empire ] [ 2 ] ) 
else 
return 
end 
else 
local sub_set2 = 4 
if pc . count_item ( 30180 ) == 0 then 
if empire == 1 then 
sub_set2 = select ( locale_quest ( 6441 ) , locale_quest ( 6443 ) , locale_quest ( 1650 ) ) 
elseif empire == 2 then 
sub_set2 = select ( locale_quest ( 6445 ) , locale_quest ( 6446 ) , locale_quest ( 1650 ) ) 
elseif empire == 3 then 
sub_set2 = select ( locale_quest ( 6449 ) , locale_quest ( 6450 ) , locale_quest ( 1650 ) ) 
end 
if sub_set2 == 3 then 
return 
end 
else 
if empire == 1 then 
sub_set2 = select ( locale_quest ( 6441 ) , locale_quest ( 6443 ) , locale_quest ( 6475 ) , locale_quest ( 1650 ) ) 
elseif empire == 2 then 
sub_set2 = select ( locale_quest ( 6445 ) , locale_quest ( 1646 ) , locale_quest ( 6475 ) , locale_quest ( 1650 ) ) 
elseif empire == 3 then 
sub_set2 = select ( locale_quest ( 6449 ) , locale_quest ( 6450 ) , locale_quest ( 6475 ) , locale_quest ( 1650 ) ) 
end 
if sub_set2 == 4 then 
return 
end 
end 
if sub_set2 ~= 4 then 
if pc . get_gold ( ) < cost then 
say_title ( locale_quest ( 6444 ) ) 
say ( locale_quest ( 6435 ) ) 
say_reward ( locale_quest ( 6437 , cost ) ) 
else 
if sub_set2 == 1 then 
say_title ( locale_quest ( 6444 ) ) 
say ( locale_quest ( 6451 ) ) 
wait ( ) 
if pc . is_dead ( ) == false then 
if empire == 1 then 
pc . warp ( 474300 , 954800 ) 
elseif empire == 2 then 
pc . warp ( 63800 , 166400 ) 
elseif empire == 3 then 
pc . warp ( 959900 , 269200 ) 
end 
else 
return 
end 
elseif sub_set2 == 2 then 
say_title ( locale_quest ( 6444 ) ) 
say ( locale_quest ( 6452 ) ) 
wait ( ) 
if pc . is_dead ( ) == false then 
if empire == 1 then 
pc . warp ( 353100 , 882900 ) 
elseif empire == 2 then 
pc . warp ( 145500 , 240000 ) 
elseif empire == 3 then 
pc . warp ( 863900 , 246000 ) 
end 
else 
return 
end 
elseif sub_set2 == 3 then 
say_title ( locale_quest ( 6444 ) ) 
say ( locale_quest ( 6452 ) ) 
wait ( ) 
if pc . is_dead ( ) == false then 
if empire == 1 then 
pc . warp ( 287800 , 799700 ) 
elseif empire == 2 then 
pc . warp ( 275500 , 800000 ) 
elseif empire == 3 then 
pc . warp ( 277000 , 788000 ) 
end 
else 
return 
end 
end 
pc . changegold ( - cost ) 
end 
end 
end 
