if get_time ( ) < pc . getqf ( "duration" ) then 
say_title ( locale_quest ( 646 ) ) 
say ( locale_quest ( 657 ) ) 
return 
end 
if pc . count_item ( 30252 ) <= 0 then 
say_title ( locale_quest ( 646 ) ) 
say ( locale_quest ( 658 ) ) 
return 
end 
say_title ( locale_quest ( 646 ) ) 
say ( locale_quest ( 659 ) ) 
pc . remove_item ( 30252 , 1 ) 
if is_test_server ( ) then 
pc . setqf ( "duration" , ( get_time ( ) + 3 ) ) 
else 
pc . setqf ( "duration" , ( get_time ( ) + ( 60 * 60 * 12 ) ) ) 
end 
wait ( ) 
local pass_percent 
if affect . get_apply_value ( 400 ) == nil then 
pass_percent = 10 
else 
pass_percent = 60 
end 
test_chat ( string . format ( "pass percent %d" , pass_percent ) ) 
local s = number ( 1 , 100 ) 
if s <= pass_percent then 
local collect_count = pc . getqf ( "collect_count" ) 
pc . setqf ( "collect_count" , collect_count + 1 ) 
affect . remove ( 400 ) 
if collect_count < 19 then 
say_title ( locale_quest ( 646 ) ) 
say ( locale_quest ( 660 ) ) 
say ( locale_quest ( 661 , ( 20 - pc . getqf ( "collect_count" ) ) ) ) 
say ( locale_quest ( 662 ) ) 
else 
pc . setqf ( "duration" , 0 ) 
say_title ( locale_quest ( 646 ) ) 
say ( locale_quest ( 667 ) ) 
local s = select ( locale_quest ( 663 ) , locale_quest ( 664 ) , locale_quest ( 665 ) ) 
if 1 == s then 
affect . add_collect ( 1 , 1100 , ( 60 * 60 * 24 * 365 * 60 ) ) 
pc . setqf ( "reward" , 1 ) 
elseif 2 == s then 
affect . add_collect ( apply . DEF_GRADE_BONUS , 140 , ( 60 * 60 * 24 * 365 * 60 ) ) 
pc . setqf ( "reward" , 2 ) 
elseif 3 == s then 
affect . add_collect ( apply . ATT_GRADE_BONUS , 60 , ( 60 * 60 * 24 * 365 * 60 ) ) 
pc . setqf ( "reward" , 3 ) 
end 
clear_letter ( ) 
set_quest_state ( "collect_quest_lv96" , "run" ) 
set_state ( "__complete" ) 
end 
return 
else 
say_title ( locale_quest ( 646 ) ) 
say ( locale_quest ( 666 ) ) 
affect . remove ( 400 ) 
return 
end 
