say_title ( locale_quest ( 9204 ) ) 
say ( locale_quest ( 10001 ) ) 
wait ( ) 
if pc . count_item ( 71025 ) == 0 then 
say_title ( locale_quest ( 9204 ) ) 
say ( locale_quest ( 10002 ) ) 
say_item ( gameforge . upgrade_refine_scroll . _220_sayItem , 71025 , "" ) 
wait ( ) 
end 
if pc . count_item ( 25040 ) == 0 then 
say_title ( locale_quest ( 9204 ) ) 
say ( locale_quest ( 10004 ) ) 
say_item ( gameforge . upgrade_refine_scroll . _60_sayItem , 25040 , "" ) 
wait ( ) 
end 
say_title ( locale_quest ( 9204 ) ) 
say ( locale_quest ( 10005 ) ) 
local s = select ( locale_quest ( 14042 ) , locale_quest ( 14043 ) ) 
if 1 == s then 
if pc . count_item ( 71025 ) > 0 and pc . count_item ( 25040 ) > 0 then 
pc . remove_item ( 71025 ) 
pc . remove_item ( 25040 ) 
pc . give_item2 ( 70039 ) 
say_title ( locale_quest ( 9204 ) ) 
say ( locale_quest ( 10006 ) ) 
say_item ( gameforge . upgrade_refine_scroll . _260_sayItem , 70039 , "" ) 
else 
say_title ( locale_quest ( 9204 ) ) 
say ( locale_quest ( 10008 ) ) 
end 
end 
