say_title ( mob_name ( 20001 ) ) 
if pc . count_item ( 30270 ) >= 10 then 
say ( locale_quest ( 936 , 9 ) ) 
pc . remove_item ( 30270 , 10 ) 
ds . give_qualification ( ) 
char_log ( pc . get_player_id ( ) , "DS_QUALIFICATION" , "SUCCESS" ) 
pc . give_item2 ( 50255 ) 
local today = math . floor ( get_global_time ( ) / 86400 ) 
pc . setf ( "dragon_soul" , "eye_timestamp" , today ) 
pc . setf ( "dragon_soul" , "eye_left" , 9 ) 
set_state ( "state_farming" ) 
else 
say ( locale_quest ( 937 ) ) 
end 
