local setting = energy_system . setting ( ) 
local need = 30 
say_title ( mob_name ( 20001 ) ) 
say ( locale_quest ( 981 , need ) ) 
wait ( ) 
if pc . get_level ( ) < 35 then 
say_title ( mob_name ( 20001 ) ) 
say ( locale_quest ( 970 ) ) 
return 
end 
if pc . count_item ( setting . energy_stone ) < need then 
say_title ( mob_name ( 20001 ) ) 
say ( locale_quest ( 982 , need ) ) 
return 
else 
say_title ( mob_name ( 20001 ) ) 
say ( locale_quest ( 983 , need ) ) 
wait ( ) 
end 
local charge = 1000 
say_title ( mob_name ( 20001 ) ) 
say ( locale_quest ( 984 , charge ) ) 
local s = select ( locale_quest ( 985 ) , locale_quest ( 986 ) ) 
if s == 2 then 
say_title ( mob_name ( 20001 ) ) 
say ( locale_quest ( 987 ) ) 
return 
end 
if pc . get_gold ( ) < charge then 
say_title ( mob_name ( 20001 ) ) 
say ( locale_quest ( 988 ) ) 
return 
end 
if pc . count_item ( setting . energy_stone ) < need then 
return 
end 
pc . change_gold ( - charge ) 
pc . remove_item ( setting . energy_stone , need ) 
if pc . getqf ( "hasExperience" ) == 0 then 
say_title ( mob_name ( 20001 ) ) 
say ( locale_quest ( 989 ) ) 
pc . give_item2 ( setting . charging_stone , 1 ) 
pc . setqf ( "hasExperience" , 1 ) 
return 
end 
local r = number ( 1 , 100 ) 
if r > 30 then 
say_title ( mob_name ( 20001 ) ) 
say ( locale_quest ( 990 ) ) 
return 
end 
say_title ( mob_name ( 20001 ) ) 
say ( locale_quest ( 991 ) ) 
pc . give_item2 ( setting . charging_stone , 1 ) 
