say_title ( locale_quest ( 2118 ) ) 
local s = number ( 1 , 7 ) 
if 1 >= s then 
say ( locale_quest ( 2095 ) ) 
elseif 2 >= s then 
say ( locale_quest ( 2096 ) ) 
elseif 3 >= s then 
say ( locale_quest ( 2097 ) ) 
elseif 4 >= s then 
say ( locale_quest ( 2098 ) ) 
elseif 5 >= s then 
say ( locale_quest ( 2099 ) ) 
elseif 6 >= s then 
say ( locale_quest ( 2100 ) ) 
elseif 7 >= s then 
say ( locale_quest ( 2101 ) ) 
end 
