if game . get_event_flag ( "spider_lair_ongoing_" .. get_channel_id ( ) ) == 1 then 
local starttime = game . get_event_flag ( "spider_lair_start_time_" .. get_channel_id ( ) ) 
local current_time = get_global_time ( ) 
if party . get_leader_pid ( ) == game . get_event_flag ( "spider_lair_leader_" .. get_channel_id ( ) ) then 
if starttime + 300 >= current_time and party . get_leader_pid ( ) == game . get_event_flag ( "spider_lair_leader_" .. get_channel_id ( ) ) and game . get_event_flag ( "spider_lair_ongoing_" .. get_channel_id ( ) ) == 1 then 
say ( locale_quest ( 8263 ) ) 
local warp = select ( locale_quest ( 2454 ) , locale_quest ( 2426 ) ) 
if warp == 1 then 
pc . warp ( 88100 , 614800 ) 
return 
end 
end 
end 
end 
