say_title ( locale_quest ( 1278 ) ) 
say ( locale_quest ( 1703 ) ) 
local u_name = input ( ) 
local u_vid = find_pc_by_name ( u_name ) 
if u_vid == 0 then 
say_title ( locale_quest ( 1710 ) ) 
say ( u_name ) 
return 
end 
local old_vid = pc . select ( u_vid , u_vid ) 
u_withdrawTime = tonumber ( pc . getqf ( "new_withdraw_time" ) ) 
u_disbandTime = tonumber ( pc . getqf ( "new_disband_time" ) ) 
pc . select ( old_vid , old_vid ) 
withdrawDelay = game . get_event_flag ( "guild_withdraw_delay" ) 
disbandDelay = game . get_event_flag ( "guild_disband_delay" ) 
say_title ( locale_quest ( 1278 ) ) 
say ( locale_quest ( 1711 ) ) 
if u_withdrawTime > 0 then 
say ( locale_quest ( 1712 , time_to_str ( u_withdrawTime ) .. locale_quest ( 1713 ) .. withdrawDelay ) ) 
end 
if u_disbandTime > 0 then 
say ( locale_quest ( 1714 , time_to_str ( u_disbandTime ) .. locale_quest ( 1715 ) .. disbandDelay ) ) 
end 
local retryTime1 = u_withdrawTime + withdrawDelay * 86400 
local retryTime2 = u_withdrawTime + disbandDelay * 86400 
local retryTime = 0 
if retryTime1 > retryTime2 then 
retryTime = retryTime1 
else 
retryTime = retryTime2 
end 
local curTime = get_time ( ) 
if curTime < retryTime then 
say ( locale_quest ( 1716 , time_to_str ( retryTime ) .. locale_quest ( 1717 ) .. ( ( retryTime - curTime ) / 3600 ) ) ) 
if is_test_server ( ) then 
local s = select ( locale_quest ( 1718 ) , locale_quest ( 39 ) ) 
if s == 1 then 
local old_vid = pc . select ( u_vid , u_vid ) 
local curTime = get_time ( ) 
pc . setqf ( "new_withdraw_time" , curTime - withdrawDelay * 86400 ) 
pc . setqf ( "new_disband_time" , curTime - disbandDelay * 86400 ) 
pc . select ( old_vid , old_vid ) 
end 
end 
else 
say ( locale_quest ( 1719 ) ) 
end 
