local g = arena . get_duel_list ( ) 
local arena_name = { } 
local arena_observer = { } 
table . foreachi ( g , 
function ( n , p ) 
arena_name [ n ] = locale_quest ( 37 , p [ 1 ] , p [ 2 ] ) 
arena_observer [ n ] = { p [ 3 ] , p [ 4 ] , p [ 5 ] } 
end 
) 
table . insert ( arena_name , locale_quest ( 39 ) ) 
table . insert ( arena_observer , 0 ) 
local count = table . getn ( g ) 
if count == 0 then 
say_title ( locale_quest ( 38 ) ) 
say ( locale_quest ( 40 ) ) 
return 
else 
say_title ( locale_quest ( 38 ) ) 
say ( locale_quest ( 41 , count ) ) 
wait ( ) 
end 
if table . getn ( g ) ~= 0 then 
local s = select_table ( arena_name ) 
if table . getn ( arena_observer ) == s then 
return 
end 
if table . getn ( arena_observer ) >= s then 
arena . add_observer ( arena_observer [ s ] [ 1 ] , arena_observer [ s ] [ 2 ] , arena_observer [ s ] [ 3 ] ) 
end 
end 
