say_title ( locale_quest ( 9204 ) ) 
say ( locale_quest ( 10000 ) ) 
wait ( ) 
if pc . count_item ( 70035 ) == 0 then 
say_title ( locale_quest ( 9204 ) ) 
say ( locale_quest ( 10009 ) ) 
say_item ( gameforge . upgrade_refine_scroll . _40_sayItem , 70035 , "" ) 
wait ( ) 
end 
if pc . count_item ( 25040 ) == 0 then 
say_title ( locale_quest ( 9204 ) ) 
say ( locale_quest ( 10011 ) ) 
say_item ( gameforge . upgrade_refine_scroll . _60_sayItem , 25040 , "" ) 
wait ( ) 
end 
say_title ( locale_quest ( 9204 ) ) 
say ( locale_quest ( 10013 ) ) 
local s = select ( locale_quest ( 14042 ) , locale_quest ( 14043 ) ) 
if 1 == s then 
if pc . get_gold ( ) < 200000 then 
say_title ( locale_quest ( 7116 ) ) 
say_reward ( locale_quest ( 2593 ) ) 
elseif pc . count_item ( 70035 ) > 0 and pc . count_item ( 25040 ) > 0 then 
pc . remove_item ( 70035 ) 
pc . remove_item ( 25040 ) 
pc . changegold ( - 200000 ) 
pc . give_item2 ( 71021 ) 
say_title ( locale_quest ( 9204 ) ) 
say ( locale_quest ( 10014 ) ) 
say_item ( gameforge . upgrade_refine_scroll . _90_sayItem , 71021 , "" ) 
else 
say_title ( locale_quest ( 9204 ) ) 
say ( locale_quest ( 9998 ) ) 
end 
end 
