local ExchangeString = { locale_quest ( 10045 ) , locale_quest ( 10046 ) , locale_quest ( 10035 ) } 
local ExchangeOption = select_table ( ExchangeString ) 
if ExchangeOption == 1 then 
say_title ( locale_quest ( 10047 ) ) 
say ( locale_quest ( 10048 , 1 , gold_format ( 1e+08 ) ) ) 
say ( locale_quest ( 10049 , 1 , 19 ) ) 
local Cheque = tonumber ( input ( ) ) 
if is_valid_number ( Cheque ) and Cheque >= 1 and Cheque <= 19 then 
local Gold = Cheque * 1e+08 
say_title ( locale_quest ( 10050 ) ) 
say ( locale_quest ( 10033 , Cheque , gold_format ( Gold ) ) ) 
if select ( locale_quest ( 10034 ) , locale_quest ( 10035 ) ) == 1 then 
if pc . get_cheque ( ) >= Cheque then 
if pc . get_gold ( ) + Gold < 1e+10 then 
pc . change_cheque ( - Cheque ) 
pc . change_gold ( Gold ) 
else 
syschat ( locale_quest ( 10060 ) ) 
end 
else 
syschat ( locale_quest ( 10060 ) ) 
end 
else return end 
else 
say ( locale_quest ( 10032 , 999 , gold_format ( 1e+10 ) ) ) 
return 
end 
elseif ExchangeOption == 2 then 
say_title ( locale_quest ( 10036 ) ) 
say ( locale_quest ( 10037 , 1 , gold_format ( 1e+08 ) ) ) 
say ( locale_quest ( 10038 , 1 , 19 ) ) 
local Cheque = tonumber ( input ( ) ) 
if is_valid_number ( Cheque ) and Cheque >= 1 and Cheque <= 19 then 
local Gold = Cheque * 1e+08 
local Tax = ( Gold * 3 ) / 100 
local GoldWithTax = Gold + Tax 
say_title ( locale_quest ( 10039 ) ) 
say ( locale_quest ( 10040 , 3 ) ) 
say ( locale_quest ( 10041 , gold_format ( GoldWithTax ) , Cheque ) ) 
if select ( locale_quest ( 10042 ) , locale_quest ( 10044 ) ) == 1 then 
if pc . get_gold ( ) >= GoldWithTax then 
if pc . get_cheque ( ) + Cheque < 999 then 
pc . change_gold ( - GoldWithTax ) 
pc . change_cheque ( Cheque ) 
else 
syschat ( locale_quest ( 10062 , ( 999 - 1 ) ) ) 
end 
else 
syschat ( locale_quest ( 10063 ) ) 
end 
else return end 
else 
say ( locale_quest ( 10032 , 999 , gold_format ( 1e+10 ) ) ) 
return 
end 
else return end 
