if pc . get_job ( ) == 0 then 
say_title ( locale_quest ( 8078 ) ) 
say ( locale_quest ( 8079 ) ) 
elseif pc . get_job ( ) == 1 then 
say_title ( locale_quest ( 8080 ) ) 
say ( locale_quest ( 8081 ) ) 
elseif pc . get_job ( ) == 2 then 
say_title ( locale_quest ( 8082 ) ) 
say ( locale_quest ( 8083 ) ) 
elseif pc . get_job ( ) == 3 then 
say_title ( locale_quest ( 8084 ) ) 
say ( locale_quest ( 8085 ) ) 
end 
select ( locale_quest ( 2454 ) ) 
setskin ( NOWINDOW ) 
